### ISSUE TITLE
improvements to Readme

### ISSUE THREAD

**Issue by KshitizSethia** [danicadamljanovic/freya#1]
In: https://github.com/danicadamljanovic/freya#setting-up-solr
- the conf folder is present in freya-annotate/src/main/resources/solr

In: https://github.com/danicadamljanovic/freya#reindexing-solr
- The first link is wrong, the query has to be _:_ instead of :

**Comment by danicadamljanovic** [comment]
Hi

Thank you for your comments, I've fixed the first one, but I am not sure I
understand the second one, what is wrong with the link? Are you talking
about this link:

http://localhost:8983/solr/update?stream.body=%3Cdelete%3E%3Cquery%3E_:_
%3C/query%3E%3C/delete%3E

Thanks
Danica

**Comment by KshitizSethia** [comment]
Danica,
The link on readme is: http://localhost:8983/solr/update?stream.body=%3Cdelete%3E%3Cquery%3E:%3C/query%3E%3C/delete%3E

It has ":" instead of "*:*". You need to escape the * like \*

For the first one, I'm not sure I have the correct conf folder, would you please verify? I haven't gotten FREyA working yet.

**Comment by danicadamljanovic** [comment]
Hi - the conf folder is now in README file - also a new edit by Rock means you don't need to use http://localhost:8983/solr/update?stream.body=%3Cdelete%3E%3Cquery%3E:%3C/query%3E%3C/delete%3E 
All you need is to run freya and call 'reindex' from localhost:8080/freya.

**Comment by danicadamljanovic** [comment]
README file is now updated, and apart from a formatting it should contain all details on how to run freya.
