### ISSUE TITLE
issue in running solr with given config

### ISSUE THREAD

**Issue by samithaj** [danicadamljanovic/freya#13]
when running solr with given config i got this error:
http://pastebin.com/PWGh2hQQ

this is after i fixed 
SEVERE: Error in xpath:java.lang.RuntimeException: solrconfig.xml missing luceneMatchVersion
error adding <luceneMatchVersion>LUCENE_40</luceneMatchVersion> tag to solrconfig.xml file stated as below url:
https://dzone.com/articles/severe-error

**Comment by samithaj** [comment]
Got it working!!!
silly mistakes by my side

**Comment by danicadamljanovic** [comment]
well done!
