### ISSUE TITLE
Locating files for creating a SPARQL endpoint

### ISSUE THREAD

**Issue by KshitizSethia** [danicadamljanovic/freya#4]
Hi,

I'm following the steps on the link http://researchsemantics.blogspot.co.uk/2012/03/set-up-your-own-sparql-endpoint-with.html

Here's the doubts I have from there:
1) where is create-owlim.xsl located? I tried finding it in Sesame 4.0, 2.8.3, 2.7.7 and 2.6.3, did not succeed. Found some xsls in the sourcecode for Sesame, but not the exact one as suggested in steps. Here are the ones I found:
./core/http/workbench/src/main/webapp/transformations/create-native-rdfs.xsl
./core/http/workbench/src/main/webapp/transformations/create-federate.xsl
./core/http/workbench/src/main/webapp/transformations/create-sparql.xsl
./core/http/workbench/src/main/webapp/transformations/create-memory-rdfs.xsl
./core/http/workbench/src/main/webapp/transformations/create-native-customrule.xsl
./core/http/workbench/src/main/webapp/transformations/create-remote.xsl
./core/http/workbench/src/main/webapp/transformations/create-native.xsl
./core/http/workbench/src/main/webapp/transformations/create.xsl
./core/http/workbench/src/main/webapp/transformations/create-native-rdfs-dt.xsl
./core/http/workbench/src/main/webapp/transformations/create-memory-rdfs-dt.xsl
./core/http/workbench/src/main/webapp/transformations/create-memory.xsl
./core/http/workbench/src/main/webapp/transformations/create-memory-customrule.xsl

2) Where can I find the .ttl files mentioned? Again, not in any releases of Sesame, but found similar ttls in source code.

**Comment by KshitizSethia** [comment]
For now I have a DBPedia SPARQL endpoint active. Instructions at http://stackoverflow.com/questions/30495427/how-do-i-query-a-sparql-endpoint-such-as-dbpedia-with-sesame

Sample query to verify you have configured DBPedia properly:
PREFIX owl: http://www.w3.org/2002/07/owl#
PREFIX xsd: http://www.w3.org/2001/XMLSchema#
PREFIX rdfs: http://www.w3.org/2000/01/rdf-schema#
PREFIX rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
PREFIX foaf: http://xmlns.com/foaf/0.1/
PREFIX dc: http://purl.org/dc/elements/1.1/
PREFIX : http://dbpedia.org/resource/
PREFIX dbpedia2: http://dbpedia.org/property/
PREFIX dbpedia: http://dbpedia.org/
PREFIX skos: http://www.w3.org/2004/02/skos/core#
SELECT ?name ?birth ?death ?person WHERE {      ?person dbo:birthPlace :Berlin .      ?person dbo:birthDate ?birth .      ?person foaf:name ?name .      ?person dbo:deathDate ?death .      FILTER (?birth < "1900-01-01"^^xsd:date) . } ORDER BY ?name

**Comment by danicadamljanovic** [comment]
You will need to use OWLIM with sesame:
http://ontotext.com/products/ontotext-graphdb/

Or just use it without OWLIM - there will be no reasoning, but it should
still work.

Or you can use your dbpedia instance as well.

**Comment by danicadamljanovic** [comment]
I have now updated the README file with instructions on how to set up Sesame, so hopefully this is simpler than setting up OWLIM.
