### ISSUE TITLE
Issue reindexing DBPedia

### ISSUE THREAD

**Issue by KshitizSethia** [danicadamljanovic/freya#5]
I'm getting an error reindexing the DBPedia proxy through FREyA. I did the following steps:

1) create dbpedia proxy endpoint in sesame-workbench.Verified it is working
2) made freya.war after changing the endpoint to dbpedia, placed it in webapps. The web page is showing up.
3) got solr running  on 8983 after taking schema.xml from freya.
4) clicked reindex option on freya homepage

I get the following error:

org.openrdf.repository.http.HTTPQueryEvaluationException: Query evaluation error: dbpedia.org: unknown error

Upon seeing the logs in freya.log I suspect this query is causing the error:

PREFIX sesame: http://www.openrdf.org/schema/sesame#
PREFIX rdfs: http://www.w3.org/2000/01/rdf-schema#
PREFIX rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
PREFIX owl: http://www.w3.org/2002/07/owl#
SELECT DISTINCT ?E ?L ?P
WHERE
{
  ?E rdf:type http://www.w3.org/2002/07/owl#Class .
    OPTIONAL {
        ?E rdfs:label ?L .
    }
}

This query has an error that P used, but never assigned.

**Comment by KshitizSethia** [comment]
When I ran the query on http://dbpedia.org/sparql I got the error details, any chance we can get them in freya logs as well? Right now I can only see "Unknown error".

**Comment by danicadamljanovic** [comment]
Hi

Is this query generated by FREyA or is it your query?
Perhaps you can create an issue describing how to reproduce it -then  I'll
have a look and try to print out the exception so it's more clear.

Danica

**Comment by KshitizSethia** [comment]
Hi Danica,

I'm getting the error when trying to reindex FREyA using the button on the homepage (therefore, query generated by FREyA). 

freya.properties points to the dbpedia proxy.

Here's the steps for creating the proxy (steps at http://stackoverflow.com/questions/30495427/how-do-i-query-a-sparql-endpoint-such-as-dbpedia-with-sesame):

![image](https://cloud.githubusercontent.com/assets/4375768/11072417/bd1c09fa-87b3-11e5-8ea1-48f6b8c4b460.png)

**Comment by danicadamljanovic** [comment]
thanks Kshitiz I will have a look.

I assume you've already updated freya.properties to repositoryURL to be
http://localhost:8080/openrdf-sesame
and the id to be dbpedia.

Also looks like there is an issue with the repository - are you sure you
can execute a sparql query using sesame-workbench and get a result back?

**Comment by KshitizSethia** [comment]
Danica, 

1) Yes, I did not change the repositoryURL, only the ID
2) Yes, I was able to execute a sample query (example query for dbpedia) and see the results in workbench.

**Comment by danicadamljanovic** [comment]
thanks Kshitiz

**Comment by KshitizSethia** [comment]
Hi Danica, were you able to reproduce this issue? Do you need any other info from me?

**Comment by danicadamljanovic** [comment]
Hi Kshitiz

I had some trouble setting up dbpedia proxy, but it seems to be working now
so I'm trying to reproduce it - I assume you were using Sesame 4.0 for this?

**Comment by danicadamljanovic** [comment]
Hi Kshitiz

I have tried reproducing this with both Sesame 4 and Sesame 2.7 workbench
and I get the same exception when I click 'reindex' on the freya's home
page:

Start reindexing ...
org.openrdf.query.resultio.QueryResultParseException: File does not contain
a binary RDF table result
End reindexing! Spent time: 2811ms

This tells me that the proxy is returning results in a format which is not
compatible with Sesame's format used by Freya so I will continue
investigating - but interestingly I have not managed to get the same error
as you.

**Comment by KshitizSethia** [comment]
Hi Danica,

I remember seeing the error you are seeing above earlier. Let me see if I can reproduce QueryResultParseException, and then get to HTTPQueryEvaluationException.

**Comment by KshitizSethia** [comment]
Hi Danica, after pulling the new code, mooney dataset works perfectly! (Thanks for updating the documentation :) )

I tried building another war pointing to the dbpedia respository
The reindexing on DBPedia goes fine (no error seen in browser), but the queries are still referencing the mooney ontology. I am closing this issue, will open another one.

**Comment by KshitizSethia** [comment]
Danica, I am getting the same error as you are. Let me open another issue.
