### ISSUE TITLE
Upgrade FREyA to work with the latest Sesame 4.0

### ISSUE THREAD

**Issue by danicadamljanovic** [danicadamljanovic/freya#7]
Update FREyA to work with Sesame 4.0.0. Anyone interested to do this please get in touch and I will offer support.

**Comment by KshitizSethia** [comment]
I am using Sesame directly from the source code (currently at 4.0.1). Let's see how this goes :)

**Comment by danicadamljanovic** [comment]
let us know!:)

**Comment by danicadamljanovic** [comment]
I've now tested Freya where the rdf repository was set up using the latest Sesame 4.0.1. and it seems to be working fine.
